module

public import MeyerGeneralProblem.Carrier.UniformDensity
public import Mathlib.Algebra.Order.Floor.Ring
import all Mathlib.Algebra.Order.Floor.Ring
public import Mathlib.Data.Finset.Sort
import all Mathlib.Data.Finset.Sort

@[expose] public section

/-!
# Bounded cluster order from finite upper density

Cluster order is expressed by the finite ordered-chain criterion: every
strictly increasing sequence of carrier points whose consecutive gaps are
strictly below the fixed scale has uniformly bounded length.  This criterion
is proved equivalent to the bound on the actual equivalence classes generated
by short gaps.  Distinct classes are separated by the fixed scale; no
separation of points inside a class is asserted.
-/

namespace MeyerGeneralProblem

noncomputable section

/-- Every nonempty finite ordered chain with consecutive gaps below `d` has
at most `q` points.  The strict gap convention is the retained cluster
convention, so a gap exactly `d` separates chains. -/
def BoundedClusterOrder (S : LocallyFiniteCarrier) (d : ℝ) (q : ℕ) : Prop :=
  ∀ (n : ℕ) (x : Fin (n + 1) → ℝ), StrictMono x →
    (∀ i, x i ∈ S.carrier) →
    (∀ i : Fin n, x i.succ - x i.castSucc < d) → n + 1 ≤ q

/-- The cluster equivalence relation generated by carrier pairs at distance
strictly below `d`. -/
def clusterSetoid (S : LocallyFiniteCarrier) (d : ℝ) : Setoid S.subtype :=
  Relation.EqvGen.setoid (fun x y ↦ |(x : ℝ) - (y : ℝ)| < d)

/-- The exact connected cluster of a carrier point. -/
def clusterClass (S : LocallyFiniteCarrier) (d : ℝ) (x : S.subtype) : Set S.subtype :=
  {y | (clusterSetoid S d).r x y}

/-- Every carrier point lies in its own cluster. -/
theorem mem_clusterClass_self (S : LocallyFiniteCarrier) (d : ℝ) (x : S.subtype) :
    x ∈ clusterClass S d x :=
  Relation.EqvGen.refl _

/-- Related points define exactly the same connected cluster. -/
theorem clusterClass_eq_of_related {S : LocallyFiniteCarrier} {d : ℝ}
    {x y : S.subtype} (hxy : (clusterSetoid S d).r x y) :
    clusterClass S d x = clusterClass S d y := by
  ext z
  constructor
  · intro hxz
    exact Relation.EqvGen.trans _ _ _ (Relation.EqvGen.symm _ _ hxy) hxz
  · intro hyz
    exact Relation.EqvGen.trans _ _ _ hxy hyz

/-- Equality of connected clusters is exactly the cluster equivalence
relation. -/
theorem clusterClass_eq_iff_related (S : LocallyFiniteCarrier) (d : ℝ)
    (x y : S.subtype) :
    clusterClass S d x = clusterClass S d y ↔ (clusterSetoid S d).r x y := by
  constructor
  · intro heq
    have h := mem_clusterClass_self S d y
    rw [← heq] at h
    exact h
  · exact clusterClass_eq_of_related

/-- A subtype interval of a locally finite real carrier is finite. -/
theorem LocallyFiniteCarrier.finite_subtype_Icc
    (S : LocallyFiniteCarrier) (x y : S.subtype) : (Set.Icc x y).Finite := by
  have hpre := (S.finite_inter_Icc (x : ℝ) (y : ℝ)).preimage
    (f := fun z : S.subtype ↦ (z : ℝ)) Subtype.val_injective.injOn
  exact hpre.subset fun z hz ↦ ⟨z.property, hz⟩

private theorem cluster_cut_invariant {S : LocallyFiniteCarrier} {d : ℝ}
    {a b x y : S.subtype} (hgap : d ≤ (b : ℝ) - (a : ℝ))
    (hempty : ∀ z : S.subtype, ¬ (a < z ∧ z < b))
    (hxy : (clusterSetoid S d).r x y) : x ≤ a ↔ y ≤ a := by
  induction hxy with
  | rel x y h =>
      have habs := abs_lt.1 h
      constructor
      · intro hxa
        by_contra hya
        have hay : a < y := lt_of_not_ge hya
        have hby : b ≤ y := by
          by_contra hnot
          exact hempty y ⟨hay, lt_of_not_ge hnot⟩
        change (x : ℝ) ≤ (a : ℝ) at hxa
        change (b : ℝ) ≤ (y : ℝ) at hby
        linarith
      · intro hya
        by_contra hxa
        have hax : a < x := lt_of_not_ge hxa
        have hbx : b ≤ x := by
          by_contra hnot
          exact hempty x ⟨hax, lt_of_not_ge hnot⟩
        change (y : ℝ) ≤ (a : ℝ) at hya
        change (b : ℝ) ≤ (x : ℝ) at hbx
        linarith
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

private theorem connected_interval_card_le
    {S : LocallyFiniteCarrier} {d : ℝ} {q : ℕ}
    (horder : BoundedClusterOrder S d q) {x y : S.subtype} (hxy : x ≤ y)
    (hconn : (clusterSetoid S d).r x y) : (Set.Icc x y).ncard ≤ q := by
  classical
  let F := (S.finite_subtype_Icc x y).toFinset
  have hxF : x ∈ F := by simp [F, hxy]
  have hFpos : 0 < F.card := Finset.card_pos.2 ⟨x, hxF⟩
  obtain ⟨n, hn⟩ : ∃ n : ℕ, F.card = n + 1 := by
    exact ⟨F.card - 1, by omega⟩
  let e : Fin (n + 1) ↪o S.subtype := F.orderEmbOfFin hn
  have he_mem (i : Fin (n + 1)) : e i ∈ Set.Icc x y := by
    have h : e i ∈ F := F.orderEmbOfFin_mem hn i
    simpa only [F, Set.Finite.mem_toFinset] using h
  have hmono : StrictMono (fun i ↦ (e i : ℝ)) := e.strictMono
  have hgap : ∀ i : Fin n, (e i.succ : ℝ) - (e i.castSucc : ℝ) < d := by
    intro i
    by_contra hnot
    have hempty : ∀ z : S.subtype, ¬ (e i.castSucc < z ∧ z < e i.succ) := by
      intro z hz
      have hzF : z ∈ F := by
        simp only [F, Set.Finite.mem_toFinset, Set.mem_Icc]
        exact ⟨(he_mem i.castSucc).1.trans hz.1.le,
          hz.2.le.trans (he_mem i.succ).2⟩
      have hzrange : z ∈ Set.range e := by
        rw [show Set.range e = (F : Set S.subtype) from F.range_orderEmbOfFin hn]
        exact hzF
      rcases hzrange with ⟨j, rfl⟩
      have hij : i.castSucc < j := e.lt_iff_lt.1 hz.1
      have hji : j < i.succ := e.lt_iff_lt.1 hz.2
      have hival : i.val < j.val := hij
      have hjval : j.val < i.val + 1 := hji
      omega
    have hcut := cluster_cut_invariant (le_of_not_gt hnot) hempty hconn
    have hyle : y ≤ e i.castSucc := hcut.1 (he_mem i.castSucc).1
    have hesucc : e i.succ ≤ e i.castSucc := (he_mem i.succ).2.trans hyle
    exact (not_le_of_gt (e.strictMono i.castSucc_lt_succ)) hesucc
  have hlength := horder n (fun i ↦ (e i : ℝ)) hmono (fun i ↦ (e i).property) hgap
  have hcard : F.card ≤ q := hn ▸ hlength
  rw [Set.ncard_eq_toFinset_card _ (S.finite_subtype_Icc x y)]
  exact hcard

private theorem clusterClass_finset_card_le
    {S : LocallyFiniteCarrier} {d : ℝ} {q : ℕ}
    (horder : BoundedClusterOrder S d q) (x : S.subtype)
    (F : Finset S.subtype) (hF : (F : Set S.subtype) ⊆ clusterClass S d x) :
    F.card ≤ q := by
  classical
  by_cases hne : F.Nonempty
  · let a := F.min' hne
    let b := F.max' hne
    have ha : (clusterSetoid S d).r x a := hF (F.min'_mem hne)
    have hb : (clusterSetoid S d).r x b := hF (F.max'_mem hne)
    have hab : (clusterSetoid S d).r a b :=
      Relation.EqvGen.trans _ _ _ (Relation.EqvGen.symm _ _ ha) hb
    have hcard := connected_interval_card_le horder (F.min'_le_max' hne) hab
    have hsubset : (F : Set S.subtype) ⊆ Set.Icc a b := by
      intro z hz
      exact ⟨F.min'_le z hz, F.le_max' z hz⟩
    have hle := Set.ncard_le_ncard hsubset (S.finite_subtype_Icc a b)
    exact (by simpa using hle : F.card ≤ (Set.Icc a b).ncard).trans hcard
  · simp [Finset.not_nonempty_iff_eq_empty.1 hne]

/-- The finite-chain criterion gives actual finite connected components,
each with at most the declared number of points. -/
theorem BoundedClusterOrder.clusterClass_finite_card_le
    {S : LocallyFiniteCarrier} {d : ℝ} {q : ℕ}
    (horder : BoundedClusterOrder S d q) (x : S.subtype) :
    (clusterClass S d x).Finite ∧ (clusterClass S d x).ncard ≤ q := by
  classical
  have hfinite : (clusterClass S d x).Finite := by
    by_contra hinfinite
    obtain ⟨T, hT, hTfinite, hTcard⟩ :=
      Set.Infinite.exists_subset_ncard_eq hinfinite (q + 1)
    have hbound := clusterClass_finset_card_le horder x hTfinite.toFinset
      (by simpa using hT)
    have hcount : T.ncard ≤ q := by
      simpa only [Set.ncard_eq_toFinset_card T hTfinite] using hbound
    omega
  refine ⟨hfinite, ?_⟩
  have hbound := clusterClass_finset_card_le horder x hfinite.toFinset
    (by simp)
  simpa only [Set.ncard_eq_toFinset_card _ hfinite] using hbound

/-- The ordered finite-chain definition is exactly the finite connected
component definition of bounded cluster order. -/
theorem boundedClusterOrder_iff_clusterClasses
    (S : LocallyFiniteCarrier) (d : ℝ) (q : ℕ) :
    BoundedClusterOrder S d q ↔
      ∀ x : S.subtype,
        (clusterClass S d x).Finite ∧ (clusterClass S d x).ncard ≤ q := by
  constructor
  · exact fun h x ↦ h.clusterClass_finite_card_le x
  · intro hclasses n x hmono hmem hgap
    let f : Fin (n + 1) → S.subtype := fun i ↦ ⟨x i, hmem i⟩
    have hfconn : ∀ i, (clusterSetoid S d).r (f 0) (f i) := by
      intro i
      induction i using Fin.induction with
      | zero => exact Relation.EqvGen.refl _
      | succ i ih =>
          apply Relation.EqvGen.trans _ _ _ ih
          apply Relation.EqvGen.rel
          change |x i.castSucc - x i.succ| < d
          rw [abs_of_neg (sub_neg.2 (hmono i.castSucc_lt_succ))]
          linarith [hgap i]
    have hf_inj : Function.Injective f := by
      intro i j hij
      exact hmono.injective (congrArg (fun z : S.subtype ↦ (z : ℝ)) hij)
    have hsubset : Set.range f ⊆ clusterClass S d (f 0) := by
      rintro z ⟨i, rfl⟩
      exact hfconn i
    have hle := Set.ncard_le_ncard hsubset (hclasses (f 0)).1
    rw [Set.ncard_range_of_injective hf_inj] at hle
    have hle' : n + 1 ≤ (clusterClass S d (f 0)).ncard := by simpa using hle
    exact hle'.trans (hclasses (f 0)).2

/-- Points in different connected clusters are separated by at least the
cluster scale, including the exact-threshold case. -/
theorem cluster_distance_ge_of_not_related
    {S : LocallyFiniteCarrier} {d : ℝ} {x y : S.subtype}
    (h : ¬ (clusterSetoid S d).r x y) : d ≤ |(x : ℝ) - (y : ℝ)| := by
  exact le_of_not_gt fun hdist ↦ h (Relation.EqvGen.rel _ _ hdist)

/-- Distinct connected clusters are mutually separated by at least the
fixed scale, for every choice of points in the two clusters. -/
theorem clusterClasses_separated {S : LocallyFiniteCarrier} {d : ℝ}
    {x y z w : S.subtype} (hne : clusterClass S d x ≠ clusterClass S d y)
    (hz : z ∈ clusterClass S d x) (hw : w ∈ clusterClass S d y) :
    d ≤ |(z : ℝ) - (w : ℝ)| := by
  apply cluster_distance_ge_of_not_related
  intro hzw
  apply hne
  apply clusterClass_eq_of_related
  exact Relation.EqvGen.trans _ _ _ hz
    (Relation.EqvGen.trans _ _ _ hzw (Relation.EqvGen.symm _ _ hw))

/-- The carrier has at most `K` points in each integer unit cell. -/
def UnitCellBound (S : LocallyFiniteCarrier) (K : ℕ) : Prop :=
  ∀ n : ℤ, windowCount S n 1 ≤ K

namespace UnitCellBound

/-- A unit-cell cap bounds every integer-aligned window of natural length. -/
theorem windowCount_nat {S : LocallyFiniteCarrier} {K : ℕ}
    (h : UnitCellBound S K) (N : ℕ) (a : ℤ) :
    windowCount S a N ≤ N * K := by
  induction N with
  | zero => simp
  | succ N ih =>
      rw [Nat.cast_succ, S.windowCount_add a N 1 (Nat.cast_nonneg _) zero_le_one]
      have hlast : windowCount S ((a : ℝ) + N) 1 ≤ K := by
        simpa using h (a + N)
      calc
        windowCount S a N + windowCount S ((a : ℝ) + N) 1 ≤ N * K + K :=
          Nat.add_le_add ih hlast
        _ = (N + 1) * K := by ring

end UnitCellBound

private theorem orderedChain_span_le {n : ℕ} (x : Fin (n + 1) → ℝ)
    {d : ℝ} (hgap : ∀ i : Fin n, x i.succ - x i.castSucc < d)
    (i : Fin (n + 1)) : x i - x 0 ≤ (i.val : ℝ) * d := by
  induction i using Fin.induction with
  | zero => simp
  | succ i ih =>
      have h := hgap i
      simp only [Fin.val_castSucc, Fin.val_succ, Nat.cast_add, Nat.cast_one] at *
      nlinarith

/-- A cap of `K` points in each unit cell gives the retained explicit chain
order `4K - 1` at scale `1/(2K)`. -/
theorem boundedClusterOrder_of_unitCellBound
    {S : LocallyFiniteCarrier} {K : ℕ} (hK : 0 < K)
    (hcap : UnitCellBound S K) :
    BoundedClusterOrder S (1 / (2 * (K : ℝ))) (4 * K - 1) := by
  intro n x hmono hmem hgap
  by_contra hnot
  have hlen : 4 * K ≤ n + 1 := by omega
  let f : Fin (4 * K) → ℝ := fun i ↦ x (Fin.castLE hlen i)
  have hf_inj : Function.Injective f :=
    hmono.injective.comp (Fin.castLE_injective hlen)
  let a : ℤ := ⌊x 0⌋
  have hden : 0 < 2 * (K : ℝ) := by positivity
  have hfwindow : Set.range f ⊆ S.carrier ∩ Set.Ico (a : ℝ) ((a : ℝ) + 3) := by
    rintro y ⟨i, rfl⟩
    refine ⟨hmem _, ?_, ?_⟩
    · exact (Int.floor_le (x 0)).trans (hmono.monotone (Fin.zero_le _))
    · have hspan := orderedChain_span_le x hgap (Fin.castLE hlen i)
      have hi : (i.val : ℝ) < 4 * (K : ℝ) := by exact_mod_cast i.isLt
      have hratio : (i.val : ℝ) * (1 / (2 * (K : ℝ))) < 2 := by
        rw [mul_one_div, div_lt_iff₀ hden]
        nlinarith
      have ha := Int.lt_floor_add_one (x 0)
      change f i < (a : ℝ) + 3
      dsimp [f, a] at *
      linarith
  have hcount : 4 * K ≤ windowCount S a 3 := by
    have h := Set.ncard_le_ncard hfwindow (S.finite_window a 3)
    rw [Set.ncard_range_of_injective hf_inj] at h
    simpa [windowCount] using h
  have hthree := hcap.windowCount_nat 3 a
  norm_num at hthree
  omega

/-- Finite numerical upper uniform Beurling density provides a uniform
unit-cell cap. -/
theorem finiteUpperDensity_exists_unitCellBound (S : LocallyFiniteCarrier)
    (hS : upperUniformBeurlingDensity S < ⊤) :
    ∃ K : ℕ, 0 < K ∧ UnitCellBound S K := by
  obtain ⟨N, hN⟩ := ENNReal.exists_nat_gt hS.ne
  have hstrict : UniformUpperDensityLT S N :=
    (uniformUpperDensityLT_iff_upperUniformBeurlingDensity_lt S
      (c := N) (Nat.cast_nonneg _)).2 (by simpa using hN)
  rcases hstrict with ⟨ε, hε, L₀, hL₀, hbound⟩
  let L := max 1 L₀
  let K : ℕ := ⌈((N : ℝ) - ε) * L⌉₊ + 1
  refine ⟨K, by dsimp [K]; omega, ?_⟩
  intro a
  have hsmall := S.windowCount_mono_length (a := a) (le_max_left 1 L₀)
  have hlarge := hbound L (le_max_right 1 L₀) a
  have hceil := Nat.le_ceil (((N : ℝ) - ε) * L)
  have hreal : (windowCount S a 1 : ℝ) ≤ (K : ℝ) := by
    have hsmall' : (windowCount S a 1 : ℝ) ≤ (windowCount S a L : ℝ) := by
      exact_mod_cast hsmall
    dsimp [K]
    push_cast
    linarith
  exact_mod_cast hreal

/-- Finite upper uniform Beurling density gives uniformly bounded cluster
order at one strictly positive fixed scale. -/
theorem finiteUpperDensity_exists_boundedClusterOrder (S : LocallyFiniteCarrier)
    (hS : upperUniformBeurlingDensity S < ⊤) :
    ∃ d : ℝ, 0 < d ∧ ∃ q : ℕ, 0 < q ∧ BoundedClusterOrder S d q := by
  obtain ⟨K, hK, hcap⟩ := finiteUpperDensity_exists_unitCellBound S hS
  refine ⟨1 / (2 * (K : ℝ)), by positivity, 4 * K - 1, by omega, ?_⟩
  exact boundedClusterOrder_of_unitCellBound hK hcap

end

end MeyerGeneralProblem
