module

public import MeyerGeneralProblem.Gram.ClosedRange
public import MeyerGeneralProblem.Atomic.SupportSubspace

@[expose] public section

/-!
# Closed ranges of Gram-whitened synthesis

Strict positivity of a coefficient Gram operator is the lower Riesz bound
needed to turn global Gram whitening into a genuine unitary parametrization
of the closed atomic support space.  This file proves the range statement
explicitly: the whitened synthesis is an isometry, has the same range as the
original synthesis, and that range is exactly the closed span of the images
of the canonical coefficient atoms.
-/

namespace MeyerGeneralProblem

noncomputable section

open scoped lp

variable {C H : Type*}
  [NormedAddCommGroup C] [InnerProductSpace ℂ C] [CompleteSpace C]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

omit [CompleteSpace H] in
/-- A synthesis range is contained in the closed span of the images of the
canonical coefficient atoms. -/
theorem synthesis_range_le_atomicSupportSubspace
    {iota : Type*} [DecidableEq iota]
    (S : CoefficientSpace iota →L[ℂ] H) :
    S.range ≤ atomicSupportSubspace (fun i ↦ S (coefficientAtom i)) := by
  rintro _ ⟨c, rfl⟩
  have h := (coefficientHilbertBasis iota).hasSum_repr c
  have hmap := S.hasSum h
  have hcoeff : ∀ i, (coefficientHilbertBasis iota).repr c i = c i := fun _ ↦ rfl
  simp only [map_smul, hcoeff] at hmap
  refine (isClosed_atomicSupportSubspace
      (fun i ↦ S (coefficientAtom i))).mem_of_tendsto hmap
    (Filter.Eventually.of_forall fun s ↦ ?_)
  exact Submodule.sum_mem
    (atomicSupportSubspace (fun i ↦ S (coefficientAtom i))) fun i hi ↦
      (atomicSupportSubspace (fun i ↦ S (coefficientAtom i))).smul_mem (c i)
        (atom_mem_atomicSupportSubspace
          (fun i ↦ S (coefficientAtom i)) i)

/-- A strictly positive coefficient Gram identifies the synthesis range with
the closed atomic support space generated by the synthesized coefficient
atoms. -/
theorem synthesis_range_eq_atomicSupportSubspace
    {iota : Type*} [DecidableEq iota]
    (S : CoefficientSpace iota →L[ℂ] H)
    (hS : IsStrictlyPositive (coefficientGram S)) :
    S.range = atomicSupportSubspace (fun i ↦ S (coefficientAtom i)) := by
  apply le_antisymm
  · exact synthesis_range_le_atomicSupportSubspace S
  · apply Submodule.topologicalClosure_minimal
    · apply Submodule.span_le.mpr
      rintro _ ⟨i, rfl⟩
      exact ⟨coefficientAtom i, rfl⟩
    · exact isClosed_range_of_coefficientGram_strictlyPositive S hS

/-- The Gram-whitened synthesis range is exactly the same closed atomic
support space. -/
theorem whitenedSynthesis_range_eq_atomicSupportSubspace
    {iota : Type*} [DecidableEq iota]
    (S : CoefficientSpace iota →L[ℂ] H)
    (hS : IsStrictlyPositive (coefficientGram S)) :
    (whitenedSynthesis S).range =
      atomicSupportSubspace (fun i ↦ S (coefficientAtom i)) := by
  rw [whitenedSynthesis_range_eq S hS,
    synthesis_range_eq_atomicSupportSubspace S hS]

/-- The closed atomic support space as a bundled closed submodule. -/
def atomicSupportClosedSubspace {iota : Type*} (v : iota → H) :
    ClosedSubmodule ℂ H where
  toSubmodule := atomicSupportSubspace v
  isClosed' := isClosed_atomicSupportSubspace v

/-- The closed atomic support generated by the images of the canonical
coefficient atoms under a synthesis map. -/
def coefficientAtomicSupport {iota : Type*}
    (S : CoefficientSpace iota →L[ℂ] H) : ClosedSubmodule ℂ H :=
  atomicSupportClosedSubspace (fun i ↦ S (coefficientAtom i))

/-- Under a strict coefficient-Gram lower bound, whitened synthesis is a
linear isometric equivalence onto the actual closed atomic support. -/
def whitenedSynthesisEquivAtomicSupport
    {iota : Type*} [DecidableEq iota]
    (S : CoefficientSpace iota →L[ℂ] H)
    (hS : IsStrictlyPositive (coefficientGram S)) :
    CoefficientSpace iota ≃ₗᵢ[ℂ] (coefficientAtomicSupport S).toSubmodule :=
  (whitenedSynthesisIsometry S hS).equivRange.trans
    (LinearIsometryEquiv.ofEq _ _
      (whitenedSynthesis_range_eq_atomicSupportSubspace S hS))

@[simp]
theorem coe_whitenedSynthesisEquivAtomicSupport_apply
    {iota : Type*} [DecidableEq iota]
    (S : CoefficientSpace iota →L[ℂ] H)
    (hS : IsStrictlyPositive (coefficientGram S))
    (c : CoefficientSpace iota) :
    ((whitenedSynthesisEquivAtomicSupport S hS c :
        (coefficientAtomicSupport S).toSubmodule) : H) =
      whitenedSynthesis S c :=
  rfl

end

end MeyerGeneralProblem
