module

public import MeyerGeneralProblem.Atomic.RieszSynthesis
public import Mathlib.Topology.Algebra.Module.ClosedSubmodule
import all Mathlib.Topology.Algebra.Module.ClosedSubmodule

@[expose] public section

/-!
# Closed atomic support subspaces

The Hilbert-space support space generated by an atomic family is its closed
linear span.  This definition is independent of the later choice of Hermite
realisation and lets the coefficient/Riesz arguments be stated once.
-/

namespace MeyerGeneralProblem

noncomputable section

variable {iota H : Type*} [NormedAddCommGroup H] [NormedSpace ℂ H]

/-- Closed linear span of an indexed atomic family. -/
def atomicSupportSubspace (v : iota → H) : Submodule ℂ H :=
  (Submodule.span ℂ (Set.range v)).topologicalClosure

theorem atom_mem_atomicSupportSubspace (v : iota → H) (i : iota) :
    v i ∈ atomicSupportSubspace v := by
  apply Submodule.le_topologicalClosure
  exact Submodule.subset_span ⟨i, rfl⟩

theorem isClosed_atomicSupportSubspace (v : iota → H) :
    IsClosed (atomicSupportSubspace v : Set H) := by
  exact Submodule.isClosed_topologicalClosure
    (Submodule.span ℂ (Set.range v))

theorem span_le_atomicSupportSubspace (v : iota → H) :
    Submodule.span ℂ (Set.range v) ≤ atomicSupportSubspace v :=
  Submodule.le_topologicalClosure _

/-- A continuous linear equivalence sends the canonical coefficient atoms to
a total atomic family. -/
theorem continuousLinearEquiv_atomicSupportSubspace_eq_top
    [DecidableEq iota]
    (S : CoefficientSpace iota ≃L[ℂ] H) :
    atomicSupportSubspace (fun i => S (coefficientAtom i)) = ⊤ := by
  have hdense : DenseRange S := S.surjective.denseRange
  have hmap := hdense.topologicalClosure_map_submodule
    (f := S.toContinuousLinearMap)
    (s := Submodule.span ℂ
      (Set.range (coefficientAtom : iota → CoefficientSpace iota)))
    coefficientAtom_dense_span
  rw [Submodule.map_span] at hmap
  have himage :
      (S.toContinuousLinearMap.toLinearMap : CoefficientSpace iota → H) ''
          Set.range (coefficientAtom : iota → CoefficientSpace iota) =
        Set.range (fun i => S (coefficientAtom i)) := by
    ext x
    simp only [Set.mem_image, Set.mem_range]
    constructor
    · rintro ⟨c, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨coefficientAtom i, ⟨i, rfl⟩, rfl⟩
  rw [himage] at hmap
  exact hmap

/-- Every Riesz basis is total in its ambient Hilbert space. -/
theorem IsRieszBasis.atomicSupportSubspace_eq_top
    [DecidableEq iota] {v : iota → H} (hv : IsRieszBasis v) :
    atomicSupportSubspace v = ⊤ := by
  rcases hv with ⟨S, hS⟩
  have hfamily : (fun i => S (coefficientAtom i)) = v :=
    funext hS
  rw [← hfamily]
  exact continuousLinearEquiv_atomicSupportSubspace_eq_top S

end

end MeyerGeneralProblem
