module

public import MeyerGeneralProblem.Distribution.MeyerSpace

@[expose] public section

/-!
# The Schwartz defect of a carrier

The defect submodule is generated by Schwartz tests vanishing on the carrier
and Fourier transforms of such tests.  Its continuous annihilator is exactly
the distributional Meyer space.
-/

open scoped FourierTransform SchwartzMap

namespace MeyerGeneralProblem

noncomputable section

/-- The Schwartz defect generated by carrier-vanishing tests and their
Fourier transforms. -/
def schwartzDefectSubmodule (S : LocallyFiniteCarrier) :
    Submodule ℂ (SchwartzMap ℝ ℂ) :=
  schwartzVanishingSubmodule S ⊔
    (schwartzVanishingSubmodule S).map
      (SchwartzMap.fourierTransformCLM ℂ).toLinearMap

/-- The intrinsic local-atomic/Fourier-local-atomic Meyer space is the
continuous annihilator of the Schwartz defect. -/
theorem distributionalMeyerSpace_eq_schwartzDefectAnnihilator
    (S : LocallyFiniteCarrier) :
    DistributionalMeyerSpace S =
      schwartzAnnihilator (schwartzDefectSubmodule S) := by
  ext T
  constructor
  · intro hT
    rw [mem_schwartzAnnihilator_iff]
    intro f hf
    obtain ⟨u, hu, v, hv, huv⟩ := Submodule.mem_sup.mp hf
    obtain ⟨g, hg, rfl⟩ := hv
    rw [← huv, map_add]
    have huZero : T u = 0 :=
      (hasLocallyAtomicAction_atomicOnCarrier S T hT.1) u hu
    have hgZero : T (FourierTransform.fourier g) = 0 := by
      simpa only [TemperedDistribution.fourier_apply] using
        (hasLocallyAtomicAction_atomicOnCarrier S
          (FourierTransform.fourier T) hT.2) g hg
    rw [huZero]
    change 0 + T (FourierTransform.fourier g) = 0
    rw [hgZero, add_zero]
  · intro hT
    have hAnn := (mem_schwartzAnnihilator_iff
      (schwartzDefectSubmodule S) T).mp hT
    rw [mem_distributionalMeyerSpace_iff]
    constructor
    · rw [← atomicOnCarrier_iff_hasLocallyAtomicAction]
      intro f hf
      exact hAnn f (show f ∈ schwartzDefectSubmodule S from
        (show schwartzVanishingSubmodule S ≤
            schwartzDefectSubmodule S from le_sup_left) hf)
    · rw [← atomicOnCarrier_iff_hasLocallyAtomicAction]
      intro f hf
      rw [TemperedDistribution.fourier_apply]
      exact hAnn (FourierTransform.fourier f)
        (show FourierTransform.fourier f ∈ schwartzDefectSubmodule S from
          (show (schwartzVanishingSubmodule S).map
              (SchwartzMap.fourierTransformCLM ℂ).toLinearMap ≤
              schwartzDefectSubmodule S from le_sup_right)
            (Submodule.mem_map_of_mem hf))

/-- Nontrivial distributional Meyer space is equivalent to proper closure
of the Schwartz defect. -/
theorem distributionalMeyerSpace_ne_bot_iff
    (S : LocallyFiniteCarrier) :
    DistributionalMeyerSpace S ≠ ⊥ ↔
      (schwartzDefectSubmodule S).topologicalClosure ≠ ⊤ := by
  rw [distributionalMeyerSpace_eq_schwartzDefectAnnihilator,
    schwartzAnnihilator_ne_bot_iff_topologicalClosure_ne_top]

end

end MeyerGeneralProblem
